sudo: false
language: ruby
rvm:
  - 2.6
before_install:
  - gem install bundler -v 2.2.19
install: bundle install --jobs=3 --retry=3
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bin/update; fi
  - bundle exec rake spec
